apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  namespace: assessment
spec:
  replicas: 15
  template:
    spec:
      containers:
        - name: app-python
          image: assessment/app-python:latest
          imagePullPolicy: Never
          env:
            - name: UVICORN_WORKERS
              value: "2" # With 8 cores, we can handle 30 workers across 15 pods easily
          resources:
            requests:
              memory: "256Mi"
              cpu: "400m" # Guaranteed 6 full cores for the app (15 * 0.4)
            limits:
              memory: "512Mi"
              cpu: "1500m" # Allow pods to burst if k6 isn't using the core
          readinessProbe:
            httpGet: { path: /readyz, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: assessment
spec:
  replicas: 4 # Increased workers to process the massive throughput of the F-series
  template:
    spec:
      containers:
        - name: worker
          image: assessment/worker:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
