apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  namespace: assessment
spec:
  replicas: 1 
  selector:
    matchLabels: { app: app-python }
  template:
    metadata:
      labels: { app: app-python }
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet # CRITICAL: Allows pod to find 'redis' while on host network
      containers:
        - name: app-python
          image: assessment/app-python:latest
          imagePullPolicy: Never
          env:
            - name: UVICORN_WORKERS
              value: "4" # Leveraging F8s_v2 8-core compute
            - name: REDIS_HOST
              value: "redis.assessment.svc.cluster.local" # Full DNS path for safety
          resources:
            limits: { cpu: "4000m", memory: "1Gi" }
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: assessment
spec:
  replicas: 4
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: assessment/worker:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: "redis.assessment.svc.cluster.local"
